export const dummyData = [
  {
    id: 1,
    name: "Henry London Smart Watch Adults",
    price: 250,
    hasDiscount: false,
    discount: 0,
    material: "Stainless Steel",
    strap: "leather",
    color: "gold",
    brand: "henry",
    gender: "male",
    picture: "/example-watch.png",
    description:
      "A sleek Henry London smartwatch for men, blending modern technology with classic style. Crafted from stainless steel with a luxurious gold finish and a premium leather strap, perfect for the sophisticated gentleman.",
  },
  {
    id: 2,
    name: "Rolex Oyster Perpetual",
    price: 5000,
    hasDiscount: true,
    discount: 10,
    material: "Gold",
    strap: "metal",
    color: "silver",
    brand: "rolex",
    gender: "male",
    picture: "/example-watch2.png",
    description:
      "An iconic Rolex Oyster Perpetual, designed for men who value timeless luxury. Made from solid gold with a silver-toned metal strap, this masterpiece offers precision and elegance at a discounted price.",
  },
  {
    id: 3,
    name: "Fossil Grant Chronograph",
    price: 180,
    hasDiscount: false,
    discount: 0,
    material: "Stainless Steel",
    strap: "leather",
    color: "brown",
    brand: "fossil",
    gender: "male",
    picture: "/example-watch3.png",
    description:
      "The Fossil Grant Chronograph combines vintage-inspired design with modern functionality. Featuring a stainless steel case and a rich brown leather strap, this men’s watch is ideal for everyday wear.",
  },
  {
    id: 4,
    name: "Casio G-Shock Classic",
    price: 120,
    hasDiscount: true,
    discount: 15,
    material: "Resin",
    strap: "rubber",
    color: "black",
    brand: "casio",
    gender: "male",
    picture: "/example-watch4.png",
    description:
      "A rugged Casio G-Shock Classic for men, built to withstand tough conditions. Made from durable resin with a black rubber strap, this watch offers practicality and style at a great discount.",
  },
  {
    id: 5,
    name: "Omega Seamaster Diver",
    price: 4500,
    hasDiscount: false,
    discount: 0,
    material: "Titanium",
    strap: "metal",
    color: "blue",
    brand: "omega",
    gender: "male",
    picture: "/example-watch2.png",
    description:
      "The Omega Seamaster Diver is a premium men’s watch for adventure seekers. Crafted from lightweight titanium with a blue metal strap, it’s designed for both underwater exploration and refined style.",
  },
  {
    id: 6,
    name: "Michael Kors Parker Watch",
    price: 300,
    hasDiscount: true,
    discount: 20,
    material: "Stainless Steel",
    strap: "metal",
    color: "rose gold",
    brand: "michael kors",
    gender: "female",
    picture: "/example-watch5.png",
    description:
      "A glamorous Michael Kors Parker Watch for women, featuring a stainless steel case and a rose gold metal strap. This chic timepiece adds a touch of elegance to any outfit, now at a special discount.",
  },
  {
    id: 7,
    name: "Garmin Fenix 6 Pro",
    price: 700,
    hasDiscount: false,
    discount: 0,
    material: "Polymer",
    strap: "silicone",
    color: "black",
    brand: "garmin",
    gender: "unisex",
    picture: "/example-watch.png",
    description:
      "The Garmin Fenix 6 Pro is a high-performance unisex smartwatch for fitness enthusiasts. Built with a sturdy polymer case and a black silicone strap, it’s perfect for tracking your active lifestyle.",
  },
  {
    id: 8,
    name: "TAG Heuer Carrera",
    price: 3800,
    hasDiscount: true,
    discount: 5,
    material: "Stainless Steel",
    strap: "leather",
    color: "black",
    brand: "tag heuer",
    gender: "male",
    picture: "/example-watch3.png",
    description:
      "A sophisticated TAG Heuer Carrera for men, blending sporty design with luxury. Made from stainless steel with a black leather strap, this watch offers timeless appeal at a slight discount.",
  },
  {
    id: 9,
    name: "Citizen Eco-Drive Promaster",
    price: 220,
    hasDiscount: false,
    discount: 0,
    material: "Stainless Steel",
    strap: "rubber",
    color: "blue",
    brand: "citizen",
    gender: "male",
    picture: "/example-watch5.png",
    description:
      "The Citizen Eco-Drive Promaster is a reliable men’s watch powered by light. With a stainless steel case, blue rubber strap, and dive-ready design, it’s a perfect blend of innovation and durability.",
  },
  {
    id: 10,
    name: "Seiko Presage Cocktail Time",
    price: 450,
    hasDiscount: true,
    discount: 10,
    material: "Stainless Steel",
    strap: "leather",
    color: "green",
    brand: "seiko",
    gender: "male",
    picture: "/example-watch.png",
    description:
      "Inspired by classic cocktails, the Seiko Presage for men features a stainless steel case and a green leather strap. This stylish watch offers a unique aesthetic at an attractive discounted price.",
  },
  {
    id: 11,
    name: "Apple Watch Series 9",
    price: 400,
    hasDiscount: false,
    discount: 0,
    material: "Aluminum",
    strap: "silicone",
    color: "white",
    brand: "apple",
    gender: "unisex",
    picture: "/example-watch4.png",
    description:
      "The Apple Watch Series 9 is a cutting-edge unisex smartwatch with a sleek aluminum case and white silicone strap. Ideal for tech-savvy individuals seeking functionality and style in one package.",
  },
  {
    id: 12,
    name: "Tissot PRX",
    price: 650,
    hasDiscount: true,
    discount: 5,
    material: "Stainless Steel",
    strap: "metal",
    color: "silver",
    brand: "tissot",
    gender: "male",
    picture: "/example-watch3.png",
    description:
      "The Tissot PRX is a modern men’s watch with a stainless steel case and silver metal strap. Combining Swiss craftsmanship with a minimalist design, it’s a versatile piece at a modest discount.",
  },
  {
    id: 13,
    name: "Hublot Big Bang",
    price: 12000,
    hasDiscount: false,
    discount: 0,
    material: "Ceramic",
    strap: "rubber",
    color: "black",
    brand: "hublot",
    gender: "male",
    picture: "/example-watch.png",
    description:
      "The Hublot Big Bang is a bold luxury watch for men, featuring a ceramic case and black rubber strap. This statement piece exemplifies cutting-edge design and exclusivity for the discerning wearer.",
  },
  {
    id: 14,
    name: "Longines HydroConquest",
    price: 1100,
    hasDiscount: true,
    discount: 8,
    material: "Stainless Steel",
    strap: "metal",
    color: "black",
    brand: "longines",
    gender: "male",
    picture: "/example-watch2.png",
    description:
      "A sporty Longines HydroConquest for men, crafted from stainless steel with a black metal strap. Designed for water enthusiasts, this watch offers elegance and durability at a discounted rate.",
  },
];
