export const dummyData = [
  {
    id: 1,
    name: "Henry London Smart Watch Adults",
    price: 250,
    hasDiscount: false,
    discount: 0,
    material: "Stainless Steel",
    strap: "leather",
    color: "gold",
    brand: "henry",
    gender: "male",
    picture: "/example-watch.png",
  },
  {
    id: 2,
    name: "Rolex Oyster Perpetual",
    price: 5000,
    hasDiscount: true,
    discount: 10,
    material: "Gold",
    strap: "metal",
    color: "silver",
    brand: "rolex",
    gender: "male",
    picture: "/example-watch2.png",
  },
  {
    id: 3,
    name: "Fossil Grant Chronograph",
    price: 180,
    hasDiscount: false,
    discount: 0,
    material: "Stainless Steel",
    strap: "leather",
    color: "brown",
    brand: "fossil",
    gender: "male",
    picture: "/example-watch3.png",
  },
  {
    id: 4,
    name: "Casio G-Shock Classic",
    price: 120,
    hasDiscount: true,
    discount: 15,
    material: "Resin",
    strap: "rubber",
    color: "black",
    brand: "casio",
    gender: "male",
    picture: "/example-watch4.png",
  },
  {
    id: 5,
    name: "Omega Seamaster Diver",
    price: 4500,
    hasDiscount: false,
    discount: 0,
    material: "Titanium",
    strap: "metal",
    color: "blue",
    brand: "omega",
    gender: "male",
    picture: "/example-watch2.png",
  },
  {
    id: 6,
    name: "Michael Kors Parker Watch",
    price: 300,
    hasDiscount: true,
    discount: 20,
    material: "Stainless Steel",
    strap: "metal",
    color: "rose gold",
    brand: "michael kors",
    gender: "female",
    picture: "/example-watch5.png",
  },
  {
    id: 7,
    name: "Garmin Fenix 6 Pro",
    price: 700,
    hasDiscount: false,
    discount: 0,
    material: "Polymer",
    strap: "silicone",
    color: "black",
    brand: "garmin",
    gender: "unisex",
    picture: "/example-watch.png",
  },
  {
    id: 8,
    name: "TAG Heuer Carrera",
    price: 3800,
    hasDiscount: true,
    discount: 5,
    material: "Stainless Steel",
    strap: "leather",
    color: "black",
    brand: "tag heuer",
    gender: "male",
    picture: "/example-watch3.png",
  },
  {
    id: 9,
    name: "Citizen Eco-Drive Promaster",
    price: 220,
    hasDiscount: false,
    discount: 0,
    material: "Stainless Steel",
    strap: "rubber",
    color: "blue",
    brand: "citizen",
    gender: "male",
    picture: "/example-watch5.png",
  },
  {
    id: 10,
    name: "Seiko Presage Cocktail Time",
    price: 450,
    hasDiscount: true,
    discount: 10,
    material: "Stainless Steel",
    strap: "leather",
    color: "green",
    brand: "seiko",
    gender: "male",
    picture: "/example-watch.png",
  },
  {
    id: 11,
    name: "Apple Watch Series 9",
    price: 400,
    hasDiscount: false,
    discount: 0,
    material: "Aluminum",
    strap: "silicone",
    color: "white",
    brand: "apple",
    gender: "unisex",
    picture: "/example-watch4.png",
  },
  {
    id: 12,
    name: "Tissot PRX",
    price: 650,
    hasDiscount: true,
    discount: 5,
    material: "Stainless Steel",
    strap: "metal",
    color: "silver",
    brand: "tissot",
    gender: "male",
    picture: "/example-watch3.png",
  },
  {
    id: 13,
    name: "Hublot Big Bang",
    price: 12000,
    hasDiscount: false,
    discount: 0,
    material: "Ceramic",
    strap: "rubber",
    color: "black",
    brand: "hublot",
    gender: "male",
    picture: "/example-watch.png",
  },
  {
    id: 14,
    name: "Longines HydroConquest",
    price: 1100,
    hasDiscount: true,
    discount: 8,
    material: "Stainless Steel",
    strap: "metal",
    color: "black",
    brand: "longines",
    gender: "male",
    picture: "/example-watch2.png",
  },
];
