import NavBar from "./_components/NavBar";
import "@/app/_styles/global.css";
import { Dosis } from "next/font/google";
import Footer from "./_components/home/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// ✅ Load Dosis font properly
const dosis = Dosis({
  subsets: ["latin"],
  weight: ["200", "400", "600", "800"], // Choose the weights you need
  variable: "--font-dosis", // Define a CSS variable for the font
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col justify-between gap-12 ${dosis.className} h-[100dvh]`}
      >
        <div className="flex flex-col">
          <NavBar />
          <main className="mt-8 pt-12">{children}</main>
        </div>
        {/* //*FOOTER */}
        <div className="bg-amber-100 bg-opacity-40">
          <Footer />
        </div>
      </body>
    </html>
  );
}
